### ISSUE TITLE
DESIGN IMAGE

### ISSUE THREAD

**Issue by Vidyamurugesh** [Q-Division-2018-2019/Team-6#3]
PLS DO IT

**Comment by PrajwalBanagar** [comment]
![img-20181006-wa0027](https://user-images.githubusercontent.com/46946896/51584830-5c92c500-1e6a-11e9-8aab-c5f9eeb463e3.jpg)

**Comment by varshakadli** [comment]
![ssb chart](https://user-images.githubusercontent.com/46948117/52930869-32043100-3370-11e9-8155-14abff1bba4c.PNG)
