### ISSUE TITLE
i need image

### ISSUE THREAD

**Issue by PrajwalBanagar** [Q-Division-2018-2019/Team-6#4]
i need an image for pertinent informtion

**Comment by PrajwalBanagar** [comment]
![picture1](https://user-images.githubusercontent.com/46946896/52175926-b33bb100-273e-11e9-8551-19893f8a5150.png)

**Comment by PrajwalBanagar** [comment]
![picture4](https://user-images.githubusercontent.com/46946896/52189988-71a71680-27cf-11e9-8f35-cfc67d15dfca.jpg)

**Comment by PrajwalBanagar** [comment]
![image](https://user-images.githubusercontent.com/46946896/52190282-9bf9d380-27d1-11e9-8069-4d074f139162.png)

**Comment by atomicrajat619** [comment]
![screenshot 6](https://user-images.githubusercontent.com/46920783/52670045-a472ac80-2f3d-11e9-88af-311c7fa9782f.png)

**Comment by atomicrajat619** [comment]
![screenshot 6](https://user-images.githubusercontent.com/46920783/52670144-db48c280-2f3d-11e9-87e9-17d7e26bb1e1.png)

**Comment by atomicrajat619** [comment]
![whatsapp image 2019-02-13 at 12 15 27 am](https://user-images.githubusercontent.com/46920783/52670363-5ca05500-2f3e-11e9-883e-b08e5c5d3217.jpeg)

**Comment by atomicrajat619** [comment]
![whatsapp image 2019-02-13 at 2 01 49 am](https://user-images.githubusercontent.com/46920783/52670440-8ce7f380-2f3e-11e9-935e-1ade2b12a386.jpeg)

**Comment by atomicrajat619** [comment]
![whatsapp image 2019-02-13 at 1 35 19 am](https://user-images.githubusercontent.com/46920783/52670498-b4d75700-2f3e-11e9-810f-f981f852f619.jpeg)

**Comment by atomicrajat619** [comment]
![whatsapp image 2019-02-13 at 2 36 43 am](https://user-images.githubusercontent.com/46920783/52670585-f2d47b00-2f3e-11e9-83ef-9b8062d092db.jpeg)

**Comment by atomicrajat619** [comment]
![screenshot 8](https://user-images.githubusercontent.com/46920783/52684197-61c7c900-2f6b-11e9-9b87-b0b48b6e1ba3.png)

**Comment by atomicrajat619** [comment]
![screenshot 12](https://user-images.githubusercontent.com/46920783/52688352-208be500-2f7c-11e9-9df9-68efc6379434.png)

**Comment by Vidyamurugesh** [comment]
![screenshot 9](https://user-images.githubusercontent.com/46933220/52929841-097a3800-336c-11e9-8273-f663e98a1674.png)
