### ISSUE TITLE
i need a photo for partinent info

### ISSUE THREAD

**Issue by atomicrajat619** [Q-Division-2018-2019/Team-6#5]

**Comment by PrajwalBanagar** [comment]
![picture1](https://user-images.githubusercontent.com/46946896/52189546-87ffa300-27cc-11e9-83ee-6507f6018f80.png)

**Comment by PrajwalBanagar** [comment]
![picture3](https://user-images.githubusercontent.com/46946896/52189801-39eb9f00-27ce-11e9-86aa-b831a831c772.png)

**Comment by varshakadli** [comment]
![ssb chart](https://user-images.githubusercontent.com/46948117/52930750-b904d980-336f-11e9-80f6-fedad9b6be09.PNG)
